### ISSUE TITLE
jest tests of search component

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#121]
We must be careful not to obsess over the component unit tests but they should be *something* at least. 

[The `Search` component](https://github.com/mdn/stumptown-renderer/blob/master/client/src/search.js) should at least be mounted and we need to mock the XHR request it triggers on first focus. 

The most important thing is to get a framework going. The tests don't have to be comprehensive but they mustn't test implementation details.

**Comment by peterbe** [comment]
Perhaps of interest @joedarc ?

**Comment by joedarc** [comment]
Sure i can take a look at this 👍

**Comment by peterbe** [comment]
> We must be careful not to obsess over the component unit tests but they should be _something_ at least.

The reason isn't that we're against tests. It's just that this early in the Stumptown project, because we're human, if you put a bunch of effort into the tests not only can it slow you down in productivity on this early-stage project, it can also (even worse) make us afraid to rip stuff out and rewrite it from scratch. 

With that said, the tests are lightweight and they only test the "outside" of the components, I think the only thing that that would break the tests is if we rename/move the component. 

This PR is also about getting the ball rolling with `react-testing-library`.

**Comment by peterbe** [comment]
This issue didn't auto-close because the description didn't say `Fixes #121`

Anyway, merge here: https://github.com/mdn/stumptown-renderer/commit/6b6e056902f865e935e3d5f68d7302f3ff5cb55a
