### ISSUE TITLE
Crashes on old node version...

### ISSUE THREAD

**Issue by Gregoor** [mdn/stumptown-renderer#134]
...which is fine, just didn't realize I had an old version running in my WSL.
I think this requires Node >= 10?

```javascript
fs.readdirSync(path.join(ROOT, directory), {withFileTypes: true})
```
(specifically the `withFileTypes: true` part).

Shall I create a PR to throw the `engines` key into package.json?

**Comment by peterbe** [comment]
> Shall I create a PR to throw the `engines` key into package.json?

Yes please!

**Comment by peterbe** [comment]
Also, put something in the README if you can.
