### ISSUE TITLE
Error with 'example' on /en-US/docs/Web/HTML/Applying_color

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#137]
Hopefully, screenshot says it all:
<img width="1505" alt="Screen Shot 2019-09-26 at 8 45 26 AM" src="https://user-images.githubusercontent.com/26739/65689240-99870b00-e03a-11e9-889b-5910f9877d3e.png">

**Comment by peterbe** [comment]
@wbamberg I *think* this depends on https://github.com/mdn/stumptown-content/issues/150#issuecomment-535180057
I.e. a reference page has a section called `examples` which, currently, hardcodes in `<h2>Examples</h2>` whereas guide pages might just have `example` and without a `<h2>` tag. 

Within the discussion of https://github.com/mdn/stumptown-content/issues/150 I think there is a solution to "merge" these two requirements. 

Or, the renderer can add a new handler for sections called `example` and refactor the code to just execute the `Example` component from here: https://github.com/mdn/stumptown-renderer/blob/7a718c47ed8a6d85d21fe124896a2f556a821ee3/client/src/ingredients/examples.js#L65
I.e. something like this:
```
import {Examples, RenderExample} from './ingredients/examples'

...

    } else if (section.type === "example") {
      return <RenderExample key={`example${i}`} example={section.value} />;

```

PS. If we do this, and have 2 exports in `ingredients/examples.js` I think the name `Example` is better than `RenderExample` and then the `Examples` component should call `Example` instead. 

Can you advice @wbamberg ?

**Comment by joedarc** [comment]
I'll wait for @wbamberg on this, I'm pretty sure if we go the suggested route there wouldn't need to be changes in stumptown-content because i had the guide pages rendering with minor adjustments at one point.

**Comment by joedarc** [comment]
Related to #157, if we're okay with just changing the renderer to accept the `example` as-is I'll get that change in.
