### ISSUE TITLE
Error boundaries

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#144]
React error boundaries help avoiding misleading client-side rendering when inevitable errors are thrown. All stumptown rendered pages are expected to work and exist on the server as a fully rendered page as is but there'll be some react'y things that can go wrong and when it happens we should be on top of it. 

Perhaps some inspiration from: https://github.com/mozilla/kuma/pull/5877

We should probably have a fluid solution that we can re-use for various components. For example, the BCD table might be wrapped individually with its own error boundary.

**Comment by peterbe** [comment]
@kenrick95 Do you mind if we use this issue here for the discussion? 

The discussion started here: https://github.com/mdn/stumptown-renderer/pull/172#issuecomment-538014382

@kenrick95 made a first implementation that uses React error boundaries to replace an empty screen with a more human screen that says "Sorry, an error occurred". Still, it's pretty useless. Why do I say that? Because the error boundaries just trades a white page for a page that says sorry. What would potentially be a LOT better is to let me continue to use the page. Although it's not that easy. It all depends on things. 

We can't have errors in the first-rendering because our `cli` will run every `render()` method of every component (if it's class otherwise just the component function) when it runs the `yarn deployment-build` command. However, errors might happen **exclusively in the browser**. I.e. in side-effects. 

For example if you do this (to any random class based component):
```diff
  render() {
+   throw new Error("Crash!")
```
then, `yarn deployment-build` will exit non-zero and nothing gets shipped to users. 

However, to simulate browser-only exceptions add this:
```diff
+ componentDidMount() {
+   throw new Error("Trouble in here");
+ }
  render() {
```
For example to the `client/src/ingredients/browser-compatibility-table/index.js:BrowserCompatibilityTable` class. 

This is what happens:
<img width="1375" alt="Screen Shot 2019-10-09 at 11 30 52 AM" src="https://user-images.githubusercontent.com/26739/66496088-5ab87280-ea88-11e9-873a-e55ef1cfad9e.png">
(Why does it happen twice by the way???)

Mind you opening http://localhost:5000/en-US/docs/Web/HTML/Element/video/ without JavaScript disabled looks like this:
<img width="1385" alt="Screen Shot 2019-10-09 at 11 32 41 AM" src="https://user-images.githubusercontent.com/26739/66496214-92271f00-ea88-11e9-9eaf-96321f35e47a.png">
(By the way, do iframes not work without JavaScript??)

That's pretty darn attractive. You can see read the content and no fancy progressive feature that might have a bug in it completely destroys the page entirely.

**Comment by peterbe** [comment]
The only way to make this happen, is to NOT call `ReactDOM.hydrate(app, container);` at all when browser React starts up. But that's not really an option. 
Also, I tried this:
```javascript
 try {
    ReactDOM.hydrate(app, container);
  } catch (ex) {
    console.warn("Error during hydration!", ex);
  }
```
but the effect is exactly like it would happen without error boundaries and we don't even get to use React tooling to write a nice error message.

**Comment by peterbe** [comment]
I'm still worried, what if someone has a weird or crappy browser (e.g. really old version or some nasty web extension) that causes a JavaScript execution error in the React runtime, then that poor user gets (more or less) a blank page rather than the HTML. The problem is that this is really really hard to simulate. If people have ideas, I'm all ears.

**Comment by peterbe** [comment]
Imagine that stumptown was entirely generated in a `cli` and we only use JavaScript for some fancy progressive features such as a search widget, or a "Sign in/mugshot", or a cool header menu that appears based on mouse interactions. Then, an unexpected error anywhere in there would't break the site. It'd behavior weirdly. Perhaps they click something on the BCD table but nothing happens. Some people might be clever and open the Web Console and notice the problem and file an issue. 

But this way, we'd at least never take away the content just because some luxurious progressive feature was buggy or because their browser has a compatibilty problem.

**Comment by peterbe** [comment]
Thoughts on this @Gregoor ?

**Comment by Gregoor** [comment]
You're making an interesting case that I didn't fully appreciate before. Thank you!

I have an idea which might just be good enough: we could save a copy of the content-nodes before hydration and then in the `<ContentErrorBoundary>` we do a raw `dangerouslySetInnerHTML` render of that, when an error occurs.
There's the question of what happens when that code errors but I think that's comparatively the lower risk.

**Comment by kenrick95** [comment]
That's a great idea!

But that would mean some of the interactive parts of the application (e.g. the search bar with suggestion list) will no longer work. Is that still acceptable?

or should the error boundary that does this technique encompass only the "content" part (document.js) and not the other parts?

**Comment by Gregoor** [comment]
Yes, good point. We'd have to think about how to contain in other parts of the page. Boundaries we could introduce are for Header, Content and Footer. Though that's just how it came to my mind, there might be more granular ways in which we can handle errors more meaningfully.

**Comment by peterbe** [comment]
I'm guilty of making this perhaps more complicated than it is. Big "large-area error boundaries" for the whole document is scary because it can hide perfectly good readable HTML just because of one little rogue widget (e.g. the BCD table). 

Then reason I voted down having one error boundary per ingredient was that the way we do ingredients is likely to change a lot. Also, there are some ingredients that don't have an fancy interactive client-side JS that can go wrong. 

@kenrick95 What do you think about pivoting to where we introduce error boundaries around the BCD table only. We can totally make it a part of the BCD table ingredient.

**Comment by kenrick95** [comment]
I see, yeah sure thing! Let's keep it small for BCD table ingredient first. :grin:
