### ISSUE TITLE
yarn workspaces can't upgrade react and react-dom

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#163]
Since we switch to yarn workspaces, I can no longer upgrade `react` and `react-dom`. Or, perhaps the instructions are just wrong. 

We now have `react-dom` (to take an example) mentioned to 2 places. 

1. in `/client/package.json`
2. in `/yarn.lock`

I tried running, at the project root: 
```
yarn upgrade react react-dom --latest
```
but that didn't change anything. Nothing happened. 

Then I tried:
```
cd client
yarn upgrade react react-dom --latest
```
but that only changed `../yarn.lock`

There are also now invalid instructions in the README about how to do package updates.

**Comment by peterbe** [comment]
Also, if we're moving away entirely from dependency on `bash`, at least for local development, we need to address the `bin/yarn-upgrade-all-reacts.sh` script. I'm not sure it's worth keeping it actually but if we're going to keep it we should turn it into a "script" in the root `package.json`.

**Comment by peterbe** [comment]
By the way, the reason we have `react` and `react-dom` in both the `client` and the `cli` is because they both need it. (One is used for the server-side rendering and one is used as a runtime). 
Perhaps it doesn't need to be like that but it's important that when we upgrade these two that we first of all do both at the same time and that we do it in tandem both for the cli and the client. It would be bad if the `client` uses a different version than the `cli`.

**Comment by Gregoor** [comment]
Unfortunately I don't have plans (or ideas) to get rid of React in CLI yet. So this definitely keeps being important, thanks for putting it on my radar.

Now what does work is `yarn upgrade-interactive --latest`, but one still needs to make sure to select the newest version for both `cli` and `client`. I'll go ahead with your advice and add a less-bashy script to the root package.json

**Comment by Gregoor** [comment]
Uch, frustrating. Looks like an [old bug](https://github.com/yarnpkg/yarn/issues/4442). So interactive-mode it is 😒 Don't think it's a biggie, but I also see that I introduced degraded DX for this with workspaces
