### ISSUE TITLE
yarn workspaces cli breaks ability to tab complete to find files

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#164]
It used to be that you could do:
```
cd cli
yarn run run ../stumptown/packaged/html/reference/elements/vid[TAB]
```
..and it would tab complete to `stumptown/packaged/html/reference/elements/video.json` because it's a normal file path on the file system relative to the current working directory. 

That breaks with the `yarn workspace cli start` because when it runs, it runs in a different working directory compared to the one you started. 
I.e. 
```bash
yarn workspace cli start stumptown/packaged/html/HTML.json
```
will fail because it's going to be looking for a file called `cli/stumptown/packaged/html/HTML.json` which doesn't exist.

**Comment by Gregoor** [comment]
We can still do
```
cd cli
yarn start ../stumptown/packaged/html/HTML.json
```

Should I document that somewhere?

**Comment by peterbe** [comment]
> Should I document that somewhere?

I think so.

This is basically advanced debugging. The only reason you'd do this is because you don't want to wait for `yarn workspace cli start` to run through every file. That can be helpful when you want to run it over and over and over when you're in a trial-and-error mode of coding. 
Basically, it's a neat trick. See if you can find a good spot for it in the README. Don't be afraid to create a new section like "Tips and tricks for advanced development" or something.
