### ISSUE TITLE
BCD renderer should handle omitted mdn_url

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-renderer#181]
The renderer for BCD [assumes that the compat data contains `mdn_url`](https://github.com/mdn/stumptown-renderer/blob/fd8d705f714bc6c01882210800e9d77b975078f4/client/src/ingredients/browser-compatibility-table/rows.js#L9), and will fail to render the page if it is missing.

But [`mdn_url` is an optional property](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-__compat-object), and is sometimes omitted: for example, for [`html.elements.link.rel`](https://github.com/mdn/browser-compat-data/blob/60d9ac7c3eb7e0521cca1d72296ff70a2a8aae94/html/elements/link.json#L575).

In these cases the table should be rendered without the feature names being links, for example: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types.

**Comment by wbamberg** [comment]
Actually it looks like it's using `mdn_url` here to get the feature name, which otherwise might be hard to get. So perhaps it might be better if `browser_compatibility` gave the next level up of the BCD JSON, like:

```
"type": "browser_compatibility",
"value": {
    "rel": {
            "__compat": {
            ...
            },
            "alternate_stylesheet": {
            ...
            }
      },
      ...
    }
}
```
rather than the current:
```
"type": "browser_compatibility",
"value": {
    "__compat": {
    ...
    },
    "alternate_stylesheet": {
    ...
    },
  ...
}
```
?

**Comment by Elchi3** [comment]
I haven't looked into how BCD is implemented in stumptown at all unfortunately. 

In the KumaScript implementation, if you provide it the query "html.elements.link.rel" it will first add the feature itself (`rel`) in https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L695
and then traverse all features below `rel`, see  https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L679

So, querying "html.elements.link.rel" returns a "feature" array to render rows:

```js
[ { "rel": compatObj }, 
  { "alternate_stylesheet": compatObj },
  { "dns-prefetch": compatObj }
  { "dns-prefetch.something": compatObj }
]
```

With this array you can then work on generating the compat rows. For the first column in such a row, a name is needed, but it isn't deriving this from the `mdn_url`. Rather the logic is like this:
(see also the `writeFeatureName` function in https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L105)

- If there is a description provided, use that. E.g. alternate_stylesheet has one, so the rendered text will be "Alternative stylesheets."
- If there is no description, use the feature identifier e.g. "dns-prefetch" and put it in code tags.
- If you have an mdn_url, linkify whatever text you have.
- Then there are special rules for when you have nested even deeper (dns-prefetch.something), but I'm not going into that now. Let me know if you're curious about that.

**Comment by Elchi3** [comment]
> So perhaps it might be better if browser_compatibility gave the next level up of the BCD JSON

Yes. I think this is correct and seems to be the missing step that I described above as:

>  In the KumaScript implementation, if you provide it the query "html.elements.link.rel" it will first add the feature itself (`rel`) in https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L695

**Comment by wbamberg** [comment]
@peterbe , what do you think about this? This is a blocker for migrating guide pages (because of pages like https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).

I think we should do this: https://github.com/mdn/stumptown-renderer/issues/181#issuecomment-540373229 but that will of course require a change in the renderer.

**Comment by peterbe** [comment]
I don't get it. "rel" in your example is variable. Is it the last part of `query.split('.').pop()`? 
Does it have to be like that? Can we not accomplish what needs to be done (related to `mdn_url`) without using variable keys?

**Comment by wbamberg** [comment]
>  Is it the last part of query.split('.').pop()?

Yes.

> Does it have to be like that? Can we not accomplish what needs to be done (related to mdn_url) without using variable keys?

It could I suppose give you something like:

```
"type": "browser_compatibility",
"value": {
    "name": "audio",
    "data": {
            "__compat": {
            ...
            },
            "autoplay": {
            ...
            }
      },
      ...
    }
}
```
...but BCD uses variable keys anyway (even in the example above it uses it for `autoplay`), and the renderer already uses them to set names for subfeatures (for example, `autoplay` in [audio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Browser_compatibility).

It only does this `mdn_url` trick for the top-level feature in a table (e.g. `audio` in the table above).
