### ISSUE TITLE
Render 'specifications' sections not implemented

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#191]
In https://github.com/mdn/stumptown-content/pull/177 @Elchi3 made it so that there's a new body section type called `specifications`. 

If you'd upgrade the git submodule, to stumptown-content, as of today you'd get this error:

```
{
  type: 'specifications',
  value: [
    {
      url: 'https://html.spec.whatwg.org/multipage/media.html#the-video-element',
      title: 'WHATWG HTML Living Standard'
    }
  ]
}
Rendering HTML failed!
      uri=/en-US/docs/Web/HTML/Element/video
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-content/packaged/html/reference/elements/video.json
Error: No idea how to handle a 'specifications' section
...
```

**Comment by Elchi3** [comment]
Yes, I'm aware of this. I want to work on this in order to learn more about stumptown-renderer.
