### ISSUE TITLE
Dependabot updates our /someproject/package.json without updating /yarn.lock

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#201]
```
~/stumptown-renderer  master ✔
▶ yarn
...

~/stumptown-renderer  master ✗
▶ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")

~/stumptown-renderer  master ✗
▶ git diff yarn.lock | gistit
Gist URL: https://gist.github.com/96c2256ec8b9bcec8cb7fa93905cfa99
```
[Here's the diff](https://gist.github.com/96c2256ec8b9bcec8cb7fa93905cfa99)

**Comment by peterbe** [comment]
Ah! [Here's the culprit!](https://github.com/mdn/stumptown-renderer/commit/36f0ac0b1a9bfb674c4ada1bf30f3b98218e25c3)
Yours truly merged that without noticing that it updated the `yarn.lock` manually without editing `yarn.lock` :(
Bad Dependabot! Does this mean Dependabot will always make this rookie mistake? Or is because how we use yarn workspaces? @Gregoor !! :)
It's somewhat understandable. Dependabot knows that `node-sass` has a new version released. So it looks for it in our repo and finds...

```
▶ rg node-sass | rg -v resolved
client/package.json:    "node-sass": "4.13.0",
yarn.lock:node-sass@4.13.0:
```
I.e. the `package.json`  and the `yarn.lock` are not in the same directory. 
Perhaps Dependabot can only work with `yarn.lock` files that are in the root?

**Comment by peterbe** [comment]
For now, I'm going to undo that Dependabot PR and do that upgrade manually. 
Until we figure out how to make Dependabot and yarn workspaces friends, we'll just have to be careful with Dependabot PRs.

**Comment by peterbe** [comment]
@Gregoor We're in this together but you're our resident yarn workspaces expert. Would you mind taking a look at this one?

**Comment by Gregoor** [comment]
Yes, thanks for tagging me (reminded me that I'm not "watching" this repo yet, now I am).

I read that Dependabot supports yarn workspaces but this commit does indeed contradict that story. Do we know of another occurence? I'm roaming the internet for people experiencing similar problems

**Comment by Gregoor** [comment]
Are we sure that commit is the culprit? I just checked out its parent and after `yarn`ing I got the same diff as you did. There's probably some bash-y way to go through every commit, run `yarn` and list the ones that produce changes, but I don't have the bash foo for that (yet?).

**Comment by Gregoor** [comment]
Yes, makes perfect sense! I think we'd then want to run this in CI then:
https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile

Unfortunately it seems to be broken for workspaces 🙈 
https://github.com/yarnpkg/yarn/issues/4098

So I think utilizing git diff is actually the best option we have rn. I'll work on a PR then!
