### ISSUE TITLE
Highlight current page in the side bar

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#230]
Inspired by this Kuma issue: https://github.com/mdn/kuma/issues/6101

Basically, if there's a link in the sidebar whose URL is the same as the current URL, it should highlight it. 

(The reason the "Date and time formats used in HTML" link is underlined is just because I hovered the mouse over it when I took the screenshot)
<img width="1034" alt="Screen Shot 2019-11-14 at 8 35 54 AM" src="https://user-images.githubusercontent.com/26739/68861696-0f623700-06ba-11ea-8833-806e14235d3a.png">

**Comment by peterbe** [comment]
Perhaps unrelated but I find it a bit annoying that the current page I'm on belongs to a collapsed section of the sidebar. 
Here's how the page starts out:
<img width="1067" alt="Screen Shot 2019-11-14 at 8 38 44 AM" src="https://user-images.githubusercontent.com/26739/68861788-37519a80-06ba-11ea-88fc-1d068bc6c53e.png">

I have to click the "> Guides" section to "feel at home". 
We use `<details>` for the HTML so we could do something like this:

```jsx
function SidebarLeaflets({ node }) {
  return (
-   <details>
+   <details open={isCurrrentURLInContent(node.content)}>
      <summary>{node.title}</summary>
      <ol>
        {node.content.map(childNode => {
          return (
            <li key={childNode.uri}>
              <Link to={childNode.uri}>{childNode.title}</Link>
            </li>
          );
        })}
      </ol>
    </details>
  );
}
```
(...but done properly)

**Comment by peterbe** [comment]
@kenrick95 Do you think you can take a look at this one?

**Comment by kenrick95** [comment]
Sure thing!
