### ISSUE TITLE
Progress bar and line-by-line files in cli

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#235]
It prints both.
<img width="1500" alt="Screen Shot 2019-11-15 at 6 41 32 AM" src="https://user-images.githubusercontent.com/26739/68947613-ef974580-0783-11ea-86f9-dca987be4f6a.png">

**Comment by peterbe** [comment]
When there's only about 100 files to go through I guess it makes sense to just list the files written. 
Also, the progress bar should not get used in `CI` (tty detection).

**Comment by peterbe** [comment]
@kenrick95 Is this something you'd be interested in? 
[We recently re-arranged the cli and the `ssr` module](https://github.com/mdn/stumptown-renderer/pull/249) and added `caporal` to be the main `cli`.

**Comment by kenrick95** [comment]
Oh wow, sure, let me investigate and catch up on this project. Thanks!
