### ISSUE TITLE
BCD table should link

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#243]
Consider https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Browser_compatibility vs. https://d27ve6vvlmvdm0.cloudfront.net/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/#Browser_compatibility
(the latter is a sample build of Project Milton and will disappear in about 30 days I think)

On developer.mozilla.org most words in the left-most column are links. E.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate
But some are not. E.g. `parse: ISO 8601 format`

Is there a `mdn_url` property we can simply use to do something like:

```jsx
{row.mdn_url ? <Link to={row.mdn_url}>{row.short_title}</Link> : <span>{row.short_title}</span>}
```

**Comment by peterbe** [comment]
Wanna take a look @joedarc 
I don't think you need to use Project Milton. I suspect the same logic would apply for the existing pages we have.

**Comment by joedarc** [comment]
@peterbe Yeah i can take a look at this. 👍

**Comment by joedarc** [comment]
@peterbe I have this working. However, the mdn_url links to https://developer.mozilla.org/. Assuming we want those links to point to stumptown instead, i could do `currentRow.mdn_url.split('/').slice(4).join('/')` but it seems kinda hacky. It does seem to be working properly, but just wanted to see if you'd rather it be done some other way.

**Comment by peterbe** [comment]
I suggest you write a function that mutates the `doc` in the cli. Kinda like we already have one that 
[fixes syntax highlighting in code snippets](https://github.com/mdn/stumptown-renderer/blob/f25773b95b9739ade053b81b65f56ea62a20ffc2/cli/index.js#L128)

We shouldn't be afraid to write little utility functions that do these mutations. If it's going to become a performance problem we'll tackle it another day. 

@wbamberg What do you think?

**Comment by peterbe** [comment]
Actually, I think you can `cp cli/syntax-highligher.js cli/browser-compatibility-table.js` and remove the Prism stuff. And wherever syntax highligting is mentioned in `cli/index.js` you copy that for this other functionality. 
We can debate the exact naming of functions and files when you have a PR. No rush.

**Comment by wbamberg** [comment]
> @wbamberg What do you think?

It's intentional that `mdn_url` in BCD is absolute, because BCD can be used in applications other than MDN, and those applications might still want to point to the MDN page for the item.

I think it's OK for stumptown-renderer to mutate this (although presumably eventually, it would be OK to use the original value?).

**Comment by peterbe** [comment]
> I think it's OK for stumptown-renderer to mutate this (although presumably eventually, it would be OK to use the original value?).

Well, then it would break links when you're on a stage build (or PR build or whatever we end up calling it)
