### ISSUE TITLE
Localization parents whose translation_of doesn't exist shouldn't be exported

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#384]
https://developer.mozilla.org/pt-BR/docs/Construindo_um_complemento for example has a `parent` that is a document with slug `Building_an_Extension` but this en-US document for slug `Building_an_Extension` is not exported at all because it's a redirect. 
In fact, it's a redirect to a document that won't be exported. See https://github.com/mdn/stumptown-renderer/issues/383

So if the localized content's parent doesn't exist at all, it shouldn't be exported at all. 
But, if the localized content's parent does exist, and it's in archivecontent, then this localized content should be dumped into `archivecontent` (which it probably already does).

**Comment by peterbe** [comment]
@escattone Yay! I'm not sure exactly where but somewhere we managed to improve the dumper so that pages like this don't get exported!
```
▶ ls -l content/files/pt-br/construindo_um_complemento
ls: content/files/pt-br/construindo_um_complemento: No such file or directory
```
Yay!
```
▶ ls -l archivecontent/files/pt-br/construindo_um_complemento
total 88
-rw-r--r--  1 peterbe  staff  33884 Apr  1 11:01 index.html
-rw-r--r--  1 peterbe  staff    147 Apr  1 11:01 index.yaml
-rw-r--r--  1 peterbe  staff    155 Apr  1 11:01 wikihistory.json
```
Yay!!

**Comment by escattone** [comment]
@peterbe Awesome! I suspect it was:
 https://github.com/mdn/stumptown-renderer/blob/473ef3a41b0aacc53e198c6ee662950ea13abc37/content/scripts/importer.js#L387.
