### ISSUE TITLE
premature check for folder existence in dumper is dangerous

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#387]
[This code](https://github.com/mdn/stumptown-renderer/blob/17b5ec693212c9b71830f9fc5599599724ccf2f3/content/scripts/importer.js#L360) makes me nervous. 
If you use `node content import --start-clean` it will first delete all of `content/files/`. Then it starts going through row-by-row. 

If it it processes `fr/web/html/element/video` first and then `fr/web/html/element` second, on that second one it's going to notice that the folder already exists and bail. 

As a matter of fact,
```
▶ ls -l content/files/fr/web/api/htmlmediaelement
total 0
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:22 canplay_event
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:22 canplaythrough_event
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:23 capturestream
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:22 durationchange_event
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:22 emptied_event
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:22 ended_event
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:23 play
drwxr-xr-x  6 peterbe  staff  192 Mar 18 15:23 volume
```

Notice how they're all folders and there's no `index.html` and `index.yaml` for that folder.

**Comment by peterbe** [comment]
Actually, I had an old copy of the `content/files` before the big async rewrite:
```
/tmp/files
▶ fd index.yaml | wc -l
   45771
```

And now:
```
stumptown-renderer/content/files  create-content-from-mysql ✗
▶ fd index.yaml | wc -l
   45024
```

**Comment by peterbe** [comment]
@Gregoor I think you might have attempted to make a solution for the fact that some slugs lead to the same folder name. E.g. 
```
let slug = 'Web/JavaScript/Reference/Statements/function*';
console.log({slug, foldername: cleanSlugForFoldername(slug)})

slug = 'Web/JavaScript/Reference/Statements/function';
console.log({slug, foldername: cleanSlugForFoldername(slug)})
```
outputs:
```
{
  slug: 'Web/JavaScript/Reference/Statements/function*',
  foldername: 'web/javascript/reference/statements/function'
}
{
  slug: 'Web/JavaScript/Reference/Statements/function',
  foldername: 'web/javascript/reference/statements/function'
}
```

In this case, we shouldn't worry about the folder but if the `index.yaml` file already exists.

**Comment by peterbe** [comment]
Actually, I wrote a little script that loops over my mysql db, exclusively for `en-us` and lists all the slugs that would get a `cleanSlugForFoldername(slug)` that is shared by another different slug:
```
[
  'Web/CSS/:left',
  'Web/CSS/:right',
  'Web/JavaScript/Reference/Statements/function*',
  'Web/JavaScript/Reference/Operators/yield*',
  'Web/JavaScript/Reference/Operators/function*'
]
```

there were many more until I realized that redirects don't matter because they don't ever become a folder on disk. 

And here's the complete list independent of locale:

```
{
  'en-US': [
    'Web/CSS/:left',
    'Web/CSS/:right',
    'Web/JavaScript/Reference/Statements/function*',
    'Web/JavaScript/Reference/Operators/yield*',
    'Web/JavaScript/Reference/Operators/function*'
  ],
  fr: [
    'Web/CSS/right',
    'Web/CSS/left',
    'Web/JavaScript/Reference/Instructions/function*',
    'Web/JavaScript/Reference/Opérateurs/yield*'
  ],
  ru: [
    'Web/Guide/AJAX/С_чего_начать?',
    'Web/JavaScript/Reference/Statements/function',
    'Web/JavaScript/Reference/Operators/function*',
    'Web/JavaScript/Reference/Operators/yield*',
    'Web/CSS/right'
  ],
  'pt-PT': [ 'Web/CSS/Como_começar/O_que_é_CSS?' ],
  ja: [
    'Web/CSS/:left',
    'Web/CSS/:right',
    'Web/JavaScript/Reference/Statements/function*',
    'Web/JavaScript/Reference/Operators/function*',
    'Web/JavaScript/Reference/Operators/yield*'
  ],
  'zh-CN': [
    'Web/CSS/::-moz-placeholder',
    'Web/JavaScript/Reference/Statements/function*',
    'Web/JavaScript/Reference/Operators/yield*',
    'Web/JavaScript/Reference/Operators/function*',
    'Web/CSS/:left',
    'Web/CSS/:right'
  ],
  de: [
    'Web/CSS/::-moz-placeholder',
    'Web/JavaScript/Reference/Operators/function*',
    'Web/JavaScript/Reference/Operators/yield*'
  ],
  es: [
    'Web/JavaScript/Referencia/Sentencias/function*',
    'Web/CSS/::-moz-placeholder',
    'Web/JavaScript/Referencia/Operadores/yield',
    'Web/CSS/:left',
    'Web/JavaScript/Referencia/Operadores/function*',
    'Web/CSS/:right'
  ],
  ko: [
    'Web/JavaScript/Reference/Operators/yield',
    'Web/JavaScript/Reference/Operators/function',
    'Web/JavaScript/Reference/Statements/function'
  ],
  'pt-BR': [
    'Web/JavaScript/Reference/Statements/function',
    'Web/JavaScript/Reference/Operators/function*',
    'Web/JavaScript/Reference/Operators/yield*'
  ],
  pl: [
    'Web/JavaScript/Referencje/Operatory/yield*',
    'Web/JavaScript/Referencje/Polecenia/function*'
  ],
  vi: [ 'Web/JavaScript/Reference/Operators/function*' ],
  tr: [ 'Web/JavaScript/Reference/Operatörler/function' ],
  uk: [
    'Web/JavaScript/Reference/Statements/function*',
    'Web/JavaScript/Reference/Operators/function*',
    'Web/JavaScript/Reference/Operators/yield*'
  ]
}
```

What we need is a solution so that `cleanSlugForFoldername` always yields the different output when the input is different. A truly 1-to-1 relationship.

**Comment by peterbe** [comment]
One thing that would work is this:
```diff
+function delicateSanitize(name) {
+  return name
+    .replace(/\*/g, "_star_")
+    .replace(/:/g, "_colon_")
+    .replace(/\?/g, "_question_");
+}
function cleanSlugForFoldername(slug) {
  return slug
    .toLowerCase()
    .split(path.sep)
+   .map(delicateSanitize)
    .map(sanitizeFilename)
    .join(path.sep);
}
```

I tried it and it totally worked. It would alleviate this problem forever. 

@Gregoor @escattone I was gonna do something fancier in the dumper but if we just do this simple string fix, we don't have to worry about doing any existence checks. What do you say?

**Comment by Gregoor** [comment]
@peterbe sounds good to me and you're absolutely right that I just did the folder check because I didn't know how to solve this more fundamentally.
What I was also thinking about (but didn't find the time to implement yet) is that it'd be nice if we could check how many documents (aka `index.yaml`s?) were created vs how many we expected to be created?

**Comment by peterbe** [comment]
Cool! What do you think @escattone ? 

I think we can do one thing at a time. 
This proposed string replace will get us unblocked in the dumper. 

In https://github.com/mdn/mdn/pull/85#issuecomment-600646866 I argued that the slug should ALWAYS match the folder name. That'd go into the builder, and not the dumper.

> What I was also thinking about (but didn't find the time to implement yet) is that it'd be nice if we could check how many documents (aka `index.yaml`s?) were created vs how many we expected to be created?

Yeah! This would be nice in the dumper. Cheap too! I'll take a look at that.

**Comment by escattone** [comment]
@peterbe 👍 Nice find, and I like your fix, thanks!

**Comment by peterbe** [comment]
Fixed in https://github.com/mdn/stumptown-renderer/commit/f7389db40f1c4b870a0a69aab16ed4eda245c9a2
