### ISSUE TITLE
Update renderer for new HTML reference recipe

### ISSUE THREAD

**Issue by ddbeck** [mdn/stumptown-renderer#65]
https://github.com/mdn/stumptown-content/pull/74 has been merged and https://github.com/mdn/stumptown-content/pull/89 is forthcoming. At some point, we'll need to update the renderer to render those pages in compliance with the new recipe.

This is a follow up to https://github.com/mdn/stumptown-content/pull/55.

**Comment by peterbe** [comment]
Is the recipe stuff in `build-json` still in flux?

**Comment by ddbeck** [comment]
Yeah, I suspect waiting until https://github.com/mdn/stumptown-content/pull/107 is merged is the right thing to do here.
